language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib libcmocka-dev:i386
script:
  - make CC="$CC" && make test
notifications:
  email: false